### ISSUE TITLE
UMSA: job are schedules with huge delay and always just one job (single dataset or collection) is run at the same time

### ISSUE THREAD

**Issue by hechth** [CESNET/usegalaxy#173]
Hi, we've observed collectively that UMSA seems to be running inly a single job per user in parallel right now - was there some change in how resources are managed and allocated? Things used to run very quick (processing of hundreds of datasets for PARC was no problem) but as of recently, things seem quite slow. Was there any change on your side? Are the jobs being sent to a different queue or so?

**Comment by martenson** [comment]
afaik these limits are in place:

```
  limits:
    - type: registered_user_concurrent_jobs
      value: 10
    - type: anonymous_user_concurrent_jobs
      value: 1
    - type: output_size
      value: 50GB
```

https://github.com/CESNET/usegalaxy/blob/12445ed9c48953eeaee1499ab46653b96c1ee4a3/group_vars/galaxyservers.yml#L80
